server:
  port: 8080
  servlet:
    context-path: /sklad

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sklad
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog-master.xml
